apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: apps
  name: httpd-deployment-dev
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-dev
  template:
    metadata:
      labels:
        app: httpd-dev
    spec:
      containers:
      - name: httpd-dev
        image: nginx:stable-alpine
        ports:
        - containerPort: 80

